# Generated by Django 4.2.1 on 2023-05-30 01:01

from django.db import migrations, models
import empleado.validators


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellido', 'nombre', 'numero_legajo']},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=30, validators=[empleado.validators.nombreValidator]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=30, validators=[empleado.validators.nombreValidator]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_legajo',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
