# Generated by Django 4.2.1 on 2023-05-30 01:01

import autor.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_alter_autor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre', 'nacionalidad']},
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(max_length=50, validators=[autor.validators.nombreValidator]),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(max_length=30, validators=[autor.validators.nombreValidator]),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=50, validators=[autor.validators.nombreValidator]),
        ),
    ]
