# Generated by Django 4.2.1 on 2023-06-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0003_alter_autor_options_alter_autor_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['id', 'apellido', 'nombre', 'nacionalidad']},
        ),
    ]
