# Generated by Django 4.2.1 on 2023-05-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='numero_legajo',
            field=models.PositiveIntegerField(),
        ),
    ]
