# Generated by Django 4.2.1 on 2023-05-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_empleado_numero_legajo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
