# Generated by Django 4.2.1 on 2023-05-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0004_initial'),
        ('libro', '0001_initial'),
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamolibro',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro'),
        ),
        migrations.AddField(
            model_name='prestamolibro',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.socio'),
        ),
    ]
