# Generated by Django 4.2.1 on 2023-05-21 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_options'),
        ('biblioteca', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamolibro',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamolibro',
            name='fecha_devolucion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 16, 44, 22, 721042)),
        ),
        migrations.AddField(
            model_name='prestamolibro',
            name='fecha_prestamos',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 16, 44, 22, 721042)),
        ),
    ]
