# Generated by Django 4.2.1 on 2023-05-24 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_alter_prestamolibro_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_devolucion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 20, 53, 7, 384138)),
        ),
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_prestamos',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 20, 53, 7, 384138)),
        ),
    ]
