# Generated by Django 4.2.1 on 2023-05-30 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_alter_prestamolibro_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_devolucion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 22, 56, 55, 475225)),
        ),
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_prestamos',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 22, 56, 55, 475225)),
        ),
    ]
