# Generated by Django 4.2.1 on 2023-05-31 01:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_alter_prestamolibro_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamolibro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_devolucion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 1, 45, 20, 934902, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_prestamos',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
