# Generated by Django 4.2.1 on 2023-06-02 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_prestamolibro_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_devolucion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 0, 25, 22, 375848, tzinfo=datetime.timezone.utc)),
        ),
    ]
