# Generated by Django 4.2.1 on 2023-06-06 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0018_alter_prestamolibro_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_devolucion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 23, 35, 52, 824459, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_prestamos',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 23, 35, 52, 824459, tzinfo=datetime.timezone.utc)),
        ),
    ]
