# Generated by Django 4.2.1 on 2023-06-06 23:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0019_alter_prestamolibro_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_devolucion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 23, 39, 32, 133952, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_prestamos',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
