# Generated by Django 4.2.1 on 2023-06-07 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0019_alter_prestamolibro_fecha_devolucion'),
        ('biblioteca', '0020_alter_prestamolibro_fecha_devolucion_and_more'),
    ]

    operations = [
    ]
