# Generated by Django 4.2.1 on 2023-06-07 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0021_merge_20230607_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_devolucion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 22, 32, 22, 278495, tzinfo=datetime.timezone.utc)),
        ),
    ]
