# Generated by Django 4.2.1 on 2023-06-09 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0023_alter_prestamolibro_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_devolucion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 19, 41, 13, 502830, tzinfo=datetime.timezone.utc)),
        ),
    ]
