# Generated by Django 4.2.1 on 2023-06-14 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0024_alter_prestamolibro_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_devolucion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 15, 57, 54, 586129, tzinfo=datetime.timezone.utc)),
        ),
    ]
