# Generated by Django 4.2.1 on 2023-06-17 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0025_alter_prestamolibro_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamolibro',
            name='fecha_devolucion',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 0, 48, 56, 847107, tzinfo=datetime.timezone.utc)),
        ),
    ]
