# Generated by Django 4.2.1 on 2023-05-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_libro_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.PositiveIntegerField(max_length=13),
        ),
    ]
