# Generated by Django 4.2.1 on 2023-05-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_alter_libro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.PositiveIntegerField(),
        ),
    ]
