# Generated by Django 4.2.1 on 2023-06-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_alter_libro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
